name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '88.0.4324.96'

    - name: Set up display
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
