name: pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ChromeDriver
      run: |
       wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/LATEST_RELEASE/chromedriver_linux64.zip
       unzip /tmp/chromedriver.zip -d /tmp


    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Start server
      run: npm start
